//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySaloon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckDucuments
    {
        public int Id { get; set; }
        public int IdWorker { get; set; }
        public int IdDocument { get; set; }
        public System.DateTime DateCheck { get; set; }
    
        public virtual Documents Documents { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
